ALTER TABLE "companies"
  ADD COLUMN IF NOT EXISTS "autoScheduleBreakEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "autoScheduleBreakFrom" TEXT NOT NULL DEFAULT '12:00',
  ADD COLUMN IF NOT EXISTS "autoScheduleBreakTo" TEXT NOT NULL DEFAULT '13:00',
  ADD COLUMN IF NOT EXISTS "autoScheduleBreakMinutes" INTEGER NOT NULL DEFAULT 60;